#server:
#  port: 8082
#
#person:
#  age: ${random.int}
#  boss: false
#  birth: 2017/12/12
#  maps: { k1: v1,k2: 12 }
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: ${person.last-name:moren}小狗
#    age: 12
#  last-name: xiaoming
